name: Build website

on:
  push

jobs:
  build-website:
    name: Build fenics2021.com
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y python3-setuptools python3-pip
        name: Install pip
      - uses: actions/checkout@v2
      - run: sudo pip3 install -r requirements.txt
        name: Install requirements
      - run: python3 builder/build.py ../_html
        name: Build website HTML
      - run: |
          cd ../_html
          git config --global user.email "symfem@mscroggs.co.uk"
          git config --global user.name "Finite Element Bot"
          git init
          git checkout -b gh-pages
          git add .
          git commit -m "Build HTML website"
          git remote add origin https://symfembot:${{ secrets.bot_github_token }}@github.com/mscroggs/fenics2021.git
          git push -u origin gh-pages --force
        name: Push website to gh-pages branch
        if: github.ref == 'refs/heads/main'
