name: Build website

on:
  push

jobs:
  style-checks:
    name: Run style checks
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y python3-flake8
        name: Install flake8
      - uses: actions/checkout@v2
      - run: python3 -m flake8 .
        name: Run flake8

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y python3-setuptools python3-pip python3-pytest
        name: Install pip
      - uses: actions/checkout@v2
      - run: sudo pip3 install -r requirements.txt
      - run: python3 -m pytest test/
        name: Run tests

  build-website:
    name: Build fenics2021.com
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y python3-setuptools python3-pip
        name: Install pip
      - uses: actions/checkout@v2
      - run: sudo pip3 install -r requirements.txt
        name: Install requirements
      - run: python3 builder/build.py _html
        name: Build website HTML

  build-and-deploy-website:
    name: Build fenics2021.com
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - run: sudo apt-get install -y python3-setuptools python3-pip
        name: Install pip
      - uses: actions/checkout@v2
      - run: sudo pip3 install -r requirements.txt
        name: Install requirements
      - run: python3 builder/build.py _html
        name: Build website HTML

      # Push to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '_html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
